from mido import Message,MidiFile,MidiTrack
def t(x:int)->int:return int(1920/x)
mid=MidiFile()
track=MidiTrack()
mid.tracks.append(track)
track.append(Message('note_on',note=64,velocity=64,time=0))
track.append(Message('note_off',note=64,velocity=127,time=t(3)))
track.append(Message('note_on',note=65,velocity=64,time=0))
track.append(Message('note_off',note=65,velocity=127,time=t(3)))
track.append(Message('note_on',note=66,velocity=64,time=0))
track.append(Message('note_off',note=66,velocity=127,time=t(3)))
mid.save('new_song.mid')